### ISSUE TITLE
TimePicker issue in ionic app after updating to ios 14 beta release

### ISSUE THREAD

**Issue by bhargavas12** [mattsteve/ionic-5-ios-14-menu-bug#1]
Hi,

After updating to ios 14 beta release we are facing issues with native timepicker in ionic4 app. 
sample images are below:

![image](https://user-images.githubusercontent.com/50710498/90785325-d6798180-e31f-11ea-8174-8418d2fe0b26.png)

![image](https://user-images.githubusercontent.com/50710498/90785405-ee510580-e31f-11ea-9745-fbc8b1e05d08.png)

any thoughts on this?

Thanks,
Bhargav

**Comment by mattsteve** [comment]
I'm not sure if you accidentally posted in the wrong repository. Ionic framework issues are logged here:
https://github.com/ionic-team/ionic-framework/issues

This repository is solely a demo I sent to the Ionic team about an issue unrelated to this - iOS 14 Beta 3 has a bug with the Ionic 5 ion-menu component.

**Comment by bhargavas12** [comment]
sorry and thanks :)
